name: Run MoveIt Middleware Benchmarks

on: [push, pull_request, workflow_dispatch]

jobs:
  run_all_benchmarks:
    name: run_all_benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    container:
      image: ghcr.io/darkusalphahydranoid/moveit_middleware_benchmark_experimental:latest
      options: --net=host
    steps:
      - name: run all benchmarks
        run: |
          lscpu
          cd /root/ws_moveit
          . /opt/ros/rolling/setup.sh
          . install/setup.sh
          sudo sysctl net | grep mem
          sudo sysctl -w "net.core.rmem_max=20971520"
          sudo sysctl -w "net.core.wmem_max=20971520"
          sudo sysctl -w "net.core.rmem_default=20971520"
          sudo sysctl -w "net.core.wmem_default=20971520"
          taskset -c 0 sh src/moveit_middleware_benchmark_experimental/scripts/run_all_benchmarks.sh -i ./src/moveit_middleware_benchmark_experimental/middleware_configurations/rmw_fastrtps/config_rmw_fastrtps.sh -d /benchmark_results -m rmw_fastrtps_cpp
          taskset -c 0 sh src/moveit_middleware_benchmark_experimental/scripts/run_all_benchmarks.sh -i ./src/moveit_middleware_benchmark_experimental/middleware_configurations/rmw_cyclonedds/config_rmw_cyclonedds.sh -d /benchmark_results -m rmw_cyclonedds_cpp
      - name: clone repo
        uses: actions/checkout@v3
      - name: add to safe directory
        run: |
          git config --global --add safe.directory /__w/moveit_middleware_benchmark_experimental/moveit_middleware_benchmark_experimental
      - name: push perception benchmark results for rmw_fastrtps to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Perception Pipeline Benchmark
          tool: 'googlecpp'
          output-file-path: /benchmark_results/scenario_perception_pipeline/rmw_fastrtps_cpp.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "rmw_fastrtps"
      - name: push simple service client benchmark results for rmw_fastrtps to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Basic Service Client Benchmark
          tool: 'googlecpp'
          output-file-path: /benchmark_results/scenario_basic_service_client/rmw_fastrtps_cpp.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "rmw_fastrtps"

      - name: push perception benchmark results for rmw_cyclonedds to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Perception Pipeline Benchmark
          tool: 'googlecpp'
          output-file-path: /benchmark_results/scenario_perception_pipeline/rmw_cyclonedds_cpp.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "rmw_cyclonedds"
      - name: push simple service client benchmark results for rme_cyclonedds to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Basic Service Client Benchmark
          tool: 'googlecpp'
          output-file-path: /benchmark_results/scenario_basic_service_client/rmw_cyclonedds_cpp.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "rmw_cyclonedds"
